### PR TITLE
Update to ubuntu:20.04 and move to python3 for pwntools

### LINKED ISSUE #35: use python3 pwntools
Looks like they now support python3
https://github.com/Gallopsled/pwntools

### PR DESCRIPTION
**Pull request by sroettger**
fixes #35

### CODE REVIEW

**Comment by sroettger** [comment]
what's the best way to test this since I changed the base images?

**Comment by sirdarckcat** [comment]
manually change the label to latest on GCR and test from there.

**Comment by sroettger** [comment]
do you know what that push error is? gateway timeout

**Comment by sroettger** [comment]
cool, this should work now. PTAL

**Comment by sroettger** [comment]
ping :)

**Pull request merged**
