### PR TITLE
fix web deployments with AddToScheme for missing resources

### PR DESCRIPTION
**Pull request by sroettger**

### CODE REVIEW

**Comment by sroettger** [comment]
This lead to errors of the form:
```
ERROR   controller.challenge    Error updating backend config for load balancer {"reconciler group": "kctf.dev", "reconciler kind": "Challenge", "name": "chalname", "namespace": "default", "Challenge ": "chalname", " with namespace ": "default", " Name: ": "chalname", " with namespace ": "default", "error": "no kind is registered for the type v1.BackendConfig in scheme \"pkg/runtime/scheme.go:100\""} 
```

**Review by sirdarckcat — APPROVED** [review]
theres several changes to kctf-test from kctf-docker - idk if this will affect installation. where did -test come from?

**Comment by sroettger** [comment]
kctf-test is my project. This is all from the ./build-and-deploy script

**Comment by sroettger** [comment]
> theres several changes to kctf-test from kctf-docker - idk if this will affect installation. where did -test come from?

I pushed another commit to undo these changes

**Pull request merged**
