### PR TITLE
annotate the domain properly

### PR DESCRIPTION
**Pull request by sirdarckcat**

### CODE REVIEW

**Comment by sirdarckcat** [comment]
maybe we can do www.chal.domain for http, wdyt?

**Comment by sroettger** [comment]
is this to distinguish between a tcp and http endpoint?
www. sounds fine too

**Review by sroettger — APPROVED** [review]

**Comment by sirdarckcat** [comment]
yep, the http load balancers and tcp load balancers need different hosts. tasks could, in theory have both

**Comment by sirdarckcat** [comment]
we can switch to www on beta

**Pull request merged**
