### PR TITLE
return if start_gce fails

### PR DESCRIPTION
**Pull request by sroettger**

### CODE REVIEW

**Comment by sirdarckcat** [comment]
why do we wanna do that? :o

wouldn't that make us miss errors?

**Comment by sroettger** [comment]
why would we continue if start_operator_gce returned an error already? It just means more unrelated errors?

**Comment by sirdarckcat** [comment]
oh but then shouldn't we return the error? like `return 1` or will return preserve errno

**Comment by sroettger** [comment]
From `help return`:
If N is omitted, the return status is that of the
last command executed within the function or script.

**Comment by sirdarckcat** [comment]
cool!

**Review by sirdarckcat — APPROVED** [review]

**Pull request merged**
